export const data=[
    {
        question:"which is my B'day month",
        option1: "Between January-March",
        option2: "Between April-Jun",
        option3: "Between July-September",
        option4: "Between September-December",
        ans:1,
    },
    {
        question:"which sport do i like most",
        option1: "Football",
        option2: "Cricket",
        option3: "Kabadi",
        option4: "Other",
        ans:1,
    },
    {
        question:"Who is my favourite cricket",
        option1: "Virat Kohli",
        option2: "Ms Dhoni",
        option3: "Rohit Sharma",
        option4: "Other",
        ans:1,
    },
    {
        question:"which social media i use a lot",
        option1: "Whatsapp",
        option2: "Instagram",
        option3: "Youtube",
        option4: "Snapchat",
        ans:1,
    },
    {
        question:"with $100billion, what would i do first",
        option1: "Foreign trip",
        option2: "Start a business",
        option3: "Put it in stock",
        option4: "Buy Supercar",
        ans:1,
    },
    {
        question:"what i do in free time mostly",
        option1: "netflix and chill",
        option2: "Reading booking",
        option3: "Sleeping",
        option4: "Go to Gym",
        ans:1,
    },
    {
        question:"what's my favourite drink",
        option1: "Tea",
        option2: "Coffee",
        option3: "Beer",
        option4: "Vodka",
        ans:1,
    },
    {
        question:"what is more important to me right now?",
        option1: "Money",
        option2: "Love",
        option3: "family & Friend",
        option4: "Carrier",
        ans:1,
    },
    {
        question:"who is my favourite footbal player?",
        option1: "Ronaldo",
        option2: "Messi",
        option3: "Both",
        option4: "None",
        ans:1,
    },
    {
        question:"Which zone of movie i watched more? ",
        option1: "Indian",
        option2: "Hollywood",
        option3: "Korean",
        option4: "Not interested in movies",
        ans:1,
    }
]
